/*
  Part of: MMUX CC Libc
  Contents: constants header
  Date: Dec  9, 2024

  Abstract

	This heaser  defines constants.  It must  be included in both  the public and
	the private headder files.

  Copyright (C) 2024, 2025 Marco Maggi <mrc.mgg@gmail.com>

  This program is free  software: you can redistribute it and/or  modify it under the
  terms  of  the  GNU General  Public  License  as  published  by the  Free  Software
  Foundation, either version 3 of the License, or (at your option) any later version.

  This program  is distributed in the  hope that it  will be useful, but  WITHOUT ANY
  WARRANTY; without  even the implied  warranty of  MERCHANTABILITY or FITNESS  FOR A
  PARTICULAR PURPOSE.  See the GNU General Public License for more details.

  You should have received  a copy of the GNU General Public  License along with this
  program.  If not, see <http://www.gnu.org/licenses/>.
*/

#ifndef MMUX_CC_LIBC_CONSTANTS_H
#define MMUX_CC_LIBC_CONSTANTS_H 1


/** --------------------------------------------------------------------
 ** Some constants.
 ** ----------------------------------------------------------------- */

#define MMUX_HAVE_LIBC_EXIT_SUCCESS	1
#define MMUX_LIBC_EXIT_SUCCESS		((mmux_libc_process_exit_status_t){ .value = mmux_libc_VALUEOF_EXIT_SUCCESS })

#define MMUX_HAVE_LIBC_EXIT_FAILURE	1
#define MMUX_LIBC_EXIT_FAILURE		((mmux_libc_process_exit_status_t){ .value = mmux_libc_VALUEOF_EXIT_FAILURE })

/* ------------------------------------------------------------------ */

#define MMUX_HAVE_LIBC_WAIT_ANY	1
#define MMUX_LIBC_WAIT_ANY		((mmux_libc_pid_t){ .value = mmux_libc_VALUEOF_WAIT_ANY })

#define MMUX_HAVE_LIBC_WAIT_MYPGRP	1
#define MMUX_LIBC_WAIT_MYPGRP		((mmux_libc_pid_t){ .value = mmux_libc_VALUEOF_WAIT_MYPGRP })

/* ------------------------------------------------------------------ */

#define MMUX_HAVE_LIBC_FD_SETSIZE	1
#define MMUX_LIBC_VALUEOF_FD_SETSIZE	mmux_libc_VALUEOF_FD_SETSIZE
#define MMUX_LIBC_FD_SETSIZE		((mmux_uint_t){ .value = mmux_libc_VALUEOF_FD_SETSIZE })


/** --------------------------------------------------------------------
 ** Networking address family.
 ** ----------------------------------------------------------------- */

m4_divert(-1)
m4_define([[[MMUX_LIBC_DEFINE_SOCKETS_ADDRESS_FAMILY_CONSTANT]]],[[[m4_dnl
m4_ifelse(mmux_libc_VALUEOF_$1,[[[MMUX_META_VALUE_UNDEFINED]]],m4_dnl
[[[/* #undef MMUX_HAVE_LIBC_$1 */]]],m4_dnl
[[[#define MMUX_HAVE_LIBC_$1	1
#define MMUX_LIBC_VALUEOF_$1	mmux_libc_VALUEOF_$1
#define MMUX_LIBC_$1	((mmux_libc_network_address_family_t){ .value = mmux_libc_VALUEOF_$1 })]]])]]])
m4_divert(0)m4_dnl
MMUX_LIBC_DEFINE_SOCKETS_ADDRESS_FAMILY_CONSTANT(AF_ALG)
MMUX_LIBC_DEFINE_SOCKETS_ADDRESS_FAMILY_CONSTANT(AF_APPLETALK)
MMUX_LIBC_DEFINE_SOCKETS_ADDRESS_FAMILY_CONSTANT(AF_AX25)
MMUX_LIBC_DEFINE_SOCKETS_ADDRESS_FAMILY_CONSTANT(AF_BLUETOOTH)
MMUX_LIBC_DEFINE_SOCKETS_ADDRESS_FAMILY_CONSTANT(AF_CAN)
MMUX_LIBC_DEFINE_SOCKETS_ADDRESS_FAMILY_CONSTANT(AF_DECnet)
MMUX_LIBC_DEFINE_SOCKETS_ADDRESS_FAMILY_CONSTANT(AF_IB)
MMUX_LIBC_DEFINE_SOCKETS_ADDRESS_FAMILY_CONSTANT(AF_INET6)
MMUX_LIBC_DEFINE_SOCKETS_ADDRESS_FAMILY_CONSTANT(AF_INET)
MMUX_LIBC_DEFINE_SOCKETS_ADDRESS_FAMILY_CONSTANT(AF_IPX)
MMUX_LIBC_DEFINE_SOCKETS_ADDRESS_FAMILY_CONSTANT(AF_KCM)
MMUX_LIBC_DEFINE_SOCKETS_ADDRESS_FAMILY_CONSTANT(AF_KEY)
MMUX_LIBC_DEFINE_SOCKETS_ADDRESS_FAMILY_CONSTANT(AF_LLC)
MMUX_LIBC_DEFINE_SOCKETS_ADDRESS_FAMILY_CONSTANT(AF_LOCAL)
MMUX_LIBC_DEFINE_SOCKETS_ADDRESS_FAMILY_CONSTANT(AF_MPLS)
MMUX_LIBC_DEFINE_SOCKETS_ADDRESS_FAMILY_CONSTANT(AF_NETLINK)
MMUX_LIBC_DEFINE_SOCKETS_ADDRESS_FAMILY_CONSTANT(AF_PACKET)
MMUX_LIBC_DEFINE_SOCKETS_ADDRESS_FAMILY_CONSTANT(AF_PPPOX)
MMUX_LIBC_DEFINE_SOCKETS_ADDRESS_FAMILY_CONSTANT(AF_RDS)
MMUX_LIBC_DEFINE_SOCKETS_ADDRESS_FAMILY_CONSTANT(AF_TIPC)
MMUX_LIBC_DEFINE_SOCKETS_ADDRESS_FAMILY_CONSTANT(AF_UNIX)
MMUX_LIBC_DEFINE_SOCKETS_ADDRESS_FAMILY_CONSTANT(AF_UNSPEC)
MMUX_LIBC_DEFINE_SOCKETS_ADDRESS_FAMILY_CONSTANT(AF_VSOCK)
MMUX_LIBC_DEFINE_SOCKETS_ADDRESS_FAMILY_CONSTANT(AF_X25)
MMUX_LIBC_DEFINE_SOCKETS_ADDRESS_FAMILY_CONSTANT(AF_XDP)


/** --------------------------------------------------------------------
 ** Networking protocol family.
 ** ----------------------------------------------------------------- */

m4_divert(-1)
m4_define([[[MMUX_LIBC_DEFINE_SOCKETS_PROTOCOL_FAMILY_CONSTANT]]],[[[m4_dnl
m4_ifelse(mmux_libc_VALUEOF_$1,[[[MMUX_META_VALUE_UNDEFINED]]],m4_dnl
[[[/* #undef MMUX_HAVE_LIBC_$1 */]]],m4_dnl
[[[#define MMUX_HAVE_LIBC_$1	1
#define MMUX_LIBC_VALUEOF_$1	mmux_libc_VALUEOF_$1
#define MMUX_LIBC_$1	((mmux_libc_network_protocol_family_t){ .value = mmux_libc_VALUEOF_$1 })]]])]]])
m4_divert(0)m4_dnl
MMUX_LIBC_DEFINE_SOCKETS_PROTOCOL_FAMILY_CONSTANT(PF_FILE)
MMUX_LIBC_DEFINE_SOCKETS_PROTOCOL_FAMILY_CONSTANT(PF_INET6)
MMUX_LIBC_DEFINE_SOCKETS_PROTOCOL_FAMILY_CONSTANT(PF_INET)
MMUX_LIBC_DEFINE_SOCKETS_PROTOCOL_FAMILY_CONSTANT(PF_LOCAL)
MMUX_LIBC_DEFINE_SOCKETS_PROTOCOL_FAMILY_CONSTANT(PF_UNIX)
MMUX_LIBC_DEFINE_SOCKETS_PROTOCOL_FAMILY_CONSTANT(PF_UNSPEC)


/** --------------------------------------------------------------------
 ** Sockets internet protocols.
 ** ----------------------------------------------------------------- */

m4_divert(-1)
m4_define([[[MMUX_LIBC_DEFINE_SOCKETS_INTERNET_PROTOCOL_CONSTANT]]],[[[m4_dnl
m4_ifelse(mmux_libc_VALUEOF_$1,[[[MMUX_META_VALUE_UNDEFINED]]],m4_dnl
[[[/* #undef MMUX_HAVE_LIBC_$1 */]]],m4_dnl
[[[#define MMUX_HAVE_LIBC_$1	1
#define MMUX_LIBC_VALUEOF_$1	mmux_libc_VALUEOF_$1
#define MMUX_LIBC_$1	((mmux_libc_socket_internet_protocol_t){ .value = mmux_libc_VALUEOF_$1 })]]])]]])
m4_divert(0)m4_dnl
MMUX_LIBC_DEFINE_SOCKETS_INTERNET_PROTOCOL_CONSTANT(IPPROTO_AH)
MMUX_LIBC_DEFINE_SOCKETS_INTERNET_PROTOCOL_CONSTANT(IPPROTO_BEETPH)
MMUX_LIBC_DEFINE_SOCKETS_INTERNET_PROTOCOL_CONSTANT(IPPROTO_COMP)
MMUX_LIBC_DEFINE_SOCKETS_INTERNET_PROTOCOL_CONSTANT(IPPROTO_DCCP)
MMUX_LIBC_DEFINE_SOCKETS_INTERNET_PROTOCOL_CONSTANT(IPPROTO_EGP)
MMUX_LIBC_DEFINE_SOCKETS_INTERNET_PROTOCOL_CONSTANT(IPPROTO_ENCAP)
MMUX_LIBC_DEFINE_SOCKETS_INTERNET_PROTOCOL_CONSTANT(IPPROTO_ESP)
MMUX_LIBC_DEFINE_SOCKETS_INTERNET_PROTOCOL_CONSTANT(IPPROTO_ETHERNET)
MMUX_LIBC_DEFINE_SOCKETS_INTERNET_PROTOCOL_CONSTANT(IPPROTO_GRE)
MMUX_LIBC_DEFINE_SOCKETS_INTERNET_PROTOCOL_CONSTANT(IPPROTO_ICMP)
MMUX_LIBC_DEFINE_SOCKETS_INTERNET_PROTOCOL_CONSTANT(IPPROTO_IDP)
MMUX_LIBC_DEFINE_SOCKETS_INTERNET_PROTOCOL_CONSTANT(IPPROTO_IGMP)
MMUX_LIBC_DEFINE_SOCKETS_INTERNET_PROTOCOL_CONSTANT(IPPROTO_IP)
MMUX_LIBC_DEFINE_SOCKETS_INTERNET_PROTOCOL_CONSTANT(IPPROTO_IPIP)
MMUX_LIBC_DEFINE_SOCKETS_INTERNET_PROTOCOL_CONSTANT(IPPROTO_IPV6)
MMUX_LIBC_DEFINE_SOCKETS_INTERNET_PROTOCOL_CONSTANT(IPPROTO_MPLS)
MMUX_LIBC_DEFINE_SOCKETS_INTERNET_PROTOCOL_CONSTANT(IPPROTO_MPTCP)
MMUX_LIBC_DEFINE_SOCKETS_INTERNET_PROTOCOL_CONSTANT(IPPROTO_MTP)
MMUX_LIBC_DEFINE_SOCKETS_INTERNET_PROTOCOL_CONSTANT(IPPROTO_PIM)
MMUX_LIBC_DEFINE_SOCKETS_INTERNET_PROTOCOL_CONSTANT(IPPROTO_PUP)
MMUX_LIBC_DEFINE_SOCKETS_INTERNET_PROTOCOL_CONSTANT(IPPROTO_RAW)
MMUX_LIBC_DEFINE_SOCKETS_INTERNET_PROTOCOL_CONSTANT(IPPROTO_RSVP)
MMUX_LIBC_DEFINE_SOCKETS_INTERNET_PROTOCOL_CONSTANT(IPPROTO_SCTP)
MMUX_LIBC_DEFINE_SOCKETS_INTERNET_PROTOCOL_CONSTANT(IPPROTO_TCP)
MMUX_LIBC_DEFINE_SOCKETS_INTERNET_PROTOCOL_CONSTANT(IPPROTO_TP)
MMUX_LIBC_DEFINE_SOCKETS_INTERNET_PROTOCOL_CONSTANT(IPPROTO_UDP)
MMUX_LIBC_DEFINE_SOCKETS_INTERNET_PROTOCOL_CONSTANT(IPPROTO_UDPLITE)


/** --------------------------------------------------------------------
 ** Socket communication styles.
 ** ----------------------------------------------------------------- */

m4_divert(-1)
m4_define([[[MMUX_LIBC_DEFINE_SOCKET_STYLE_CONSTANT]]],[[[m4_dnl
m4_ifelse(mmux_libc_VALUEOF_$1,[[[MMUX_META_VALUE_UNDEFINED]]],m4_dnl
[[[/* #undef MMUX_HAVE_LIBC_$1 */]]],m4_dnl
[[[#define MMUX_HAVE_LIBC_$1	1
#define MMUX_LIBC_VALUEOF_$1	mmux_libc_VALUEOF_$1
#define MMUX_LIBC_$1	((mmux_libc_socket_communication_style_t){ .value = mmux_libc_VALUEOF_$1 })]]])]]])
m4_divert(0)m4_dnl
MMUX_LIBC_DEFINE_SOCKET_STYLE_CONSTANT(SOCK_DCCP)
MMUX_LIBC_DEFINE_SOCKET_STYLE_CONSTANT(SOCK_DGRAM)
MMUX_LIBC_DEFINE_SOCKET_STYLE_CONSTANT(SOCK_PACKET)
MMUX_LIBC_DEFINE_SOCKET_STYLE_CONSTANT(SOCK_RAW)
MMUX_LIBC_DEFINE_SOCKET_STYLE_CONSTANT(SOCK_RDM)
MMUX_LIBC_DEFINE_SOCKET_STYLE_CONSTANT(SOCK_SEQPACKET)
MMUX_LIBC_DEFINE_SOCKET_STYLE_CONSTANT(SOCK_STREAM)

/* These are Linux-specific flags that can be bitwise ORed to the style constant, see
   socket(2). */
MMUX_LIBC_DEFINE_SOCKET_STYLE_CONSTANT(SOCK_CLOEXEC)
MMUX_LIBC_DEFINE_SOCKET_STYLE_CONSTANT(SOCK_NONBLOCK)


/** --------------------------------------------------------------------
 ** Socket shutdown modes.
 ** ----------------------------------------------------------------- */

m4_divert(-1)
m4_define([[[MMUX_LIBC_DEFINE_SOCKET_SHUTDOWN_MODE_CONSTANT]]],[[[m4_dnl
m4_ifelse(mmux_libc_VALUEOF_$1,[[[MMUX_META_VALUE_UNDEFINED]]],m4_dnl
[[[/* #undef MMUX_HAVE_LIBC_$1 */]]],m4_dnl
[[[#define MMUX_HAVE_LIBC_$1	1
#define MMUX_LIBC_VALUEOF_$1	mmux_libc_VALUEOF_$1
#define MMUX_LIBC_$1	((mmux_libc_socket_shutdown_mode_t){ .value = mmux_libc_VALUEOF_$1 })]]])]]])
m4_divert(0)m4_dnl
MMUX_LIBC_DEFINE_SOCKET_SHUTDOWN_MODE_CONSTANT(SHUT_RDWR)
MMUX_LIBC_DEFINE_SOCKET_SHUTDOWN_MODE_CONSTANT(SHUT_RD)
MMUX_LIBC_DEFINE_SOCKET_SHUTDOWN_MODE_CONSTANT(SHUT_WR)


/** --------------------------------------------------------------------
 ** Sockets IPv4 addresses.
 ** ----------------------------------------------------------------- */

/* The standard defines:
 *
 *    struct in_addr { uint32_t s_addr; };
 *
 * the "INADDR_*"  constants are  the HOST  byteorder 32-bit  values of  the "s_addr"
 * field.
 */

m4_divert(-1)
m4_define([[[MMUX_LIBC_DEFINE_SOCKETS_IPFOUR_KNOWN_ADDRESS_CONSTANT]]],[[[m4_dnl
m4_ifelse(mmux_libc_VALUEOF_$1,[[[MMUX_META_VALUE_UNDEFINED]]],m4_dnl
[[[/* #undef MMUX_HAVE_LIBC_$1 */]]],m4_dnl
[[[#define MMUX_HAVE_LIBC_$1	1
#define MMUX_LIBC_VALUEOF_$1	mmux_standard_uint32_literal(mmux_libc_VALUEOF_$1)
#define MMUX_LIBC_$1	((mmux_libc_host_byteorder_uint32_t) { .value = MMUX_LIBC_VALUEOF_$1 }) ]]])]]])
m4_divert(0)m4_dnl
MMUX_LIBC_DEFINE_SOCKETS_IPFOUR_KNOWN_ADDRESS_CONSTANT(INADDR_ANY)
MMUX_LIBC_DEFINE_SOCKETS_IPFOUR_KNOWN_ADDRESS_CONSTANT(INADDR_BROADCAST)
MMUX_LIBC_DEFINE_SOCKETS_IPFOUR_KNOWN_ADDRESS_CONSTANT(INADDR_LOOPBACK)
MMUX_LIBC_DEFINE_SOCKETS_IPFOUR_KNOWN_ADDRESS_CONSTANT(INADDR_NONE)


/** --------------------------------------------------------------------
 ** Errno codes.
 ** ----------------------------------------------------------------- */

m4_divert(-1)
m4_define([[[MMUX_LIBC_DEFINE_ERRNO_CONSTANT]]],[[[m4_ifelse(mmux_libc_VALUEOF_$1,[[[MMUX_META_VALUE_UNDEFINED]]],m4_dnl
[[[/* #undef MMUX_HAVE_LIBC_$1 */]]],m4_dnl
[[[#define MMUX_HAVE_LIBC_$1	1
#define MMUX_LIBC_VALUEOF_$1	mmux_libc_VALUEOF_$1
#define MMUX_LIBC_$1		(mmux_libc_errno(mmux_libc_VALUEOF_$1))]]])]]])
m4_divert(0)m4_dnl

MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EPERM)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENOENT)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ESRCH)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EINTR)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EIO)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENXIO)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(E2BIG)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENOEXEC)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EBADF)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ECHILD)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EAGAIN)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENOMEM)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EACCES)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EFAULT)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENOTBLK)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EBUSY)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EEXIST)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EXDEV)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENODEV)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENOTDIR)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EISDIR)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EINVAL)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENFILE)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EMFILE)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENOTTY)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ETXTBSY)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EFBIG)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENOSPC)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ESPIPE)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EROFS)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EMLINK)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EPIPE)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EDOM)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ERANGE)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EDEADLK)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENAMETOOLONG)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENOLCK)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENOTSUP)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENOSYS)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENOTEMPTY)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ELOOP)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EWOULDBLOCK)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENOMSG)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EIDRM)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ECHRNG)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EL2NSYNC)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EL3HLT)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EL3RST)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ELNRNG)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EUNATCH)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENOCSI)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EL2HLT)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EBADE)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EBADR)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EXFULL)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENOANO)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EBADRQC)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EBADSLT)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EDEADLOCK)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EBFONT)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENOSTR)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENODATA)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ETIME)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENOSR)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENONET)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENOPKG)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EREMOTE)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENOLINK)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EADV)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ESRMNT)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ECOMM)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EPROTO)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EMULTIHOP)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EDOTDOT)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EBADMSG)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EOVERFLOW)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENOTUNIQ)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EBADFD)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EREMCHG)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ELIBACC)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ELIBBAD)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ELIBSCN)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ELIBMAX)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ELIBEXEC)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EILSEQ)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ERESTART)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ESTRPIPE)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EUSERS)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENOTSOCK)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EDESTADDRREQ)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EMSGSIZE)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EPROTOTYPE)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENOPROTOOPT)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EPROTONOSUPPORT)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ESOCKTNOSUPPORT)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EOPNOTSUPP)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EPFNOSUPPORT)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EAFNOSUPPORT)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EADDRINUSE)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EADDRNOTAVAIL)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENETDOWN)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENETUNREACH)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENETRESET)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ECONNABORTED)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ECONNRESET)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENOBUFS)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EISCONN)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENOTCONN)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ESHUTDOWN)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ETOOMANYREFS)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ETIMEDOUT)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ECONNREFUSED)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EHOSTDOWN)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EHOSTUNREACH)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EALREADY)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EINPROGRESS)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ESTALE)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EUCLEAN)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENOTNAM)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENAVAIL)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EISNAM)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EREMOTEIO)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EDQUOT)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENOMEDIUM)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EMEDIUMTYPE)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ECANCELED)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENOKEY)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EKEYEXPIRED)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EKEYREVOKED)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EKEYREJECTED)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(EOWNERDEAD)
MMUX_LIBC_DEFINE_ERRNO_CONSTANT(ENOTRECOVERABLE)


/** --------------------------------------------------------------------
 ** System configuration.
 ** ----------------------------------------------------------------- */

m4_divert(-1)
m4_define([[[MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT]]],[[[m4_dnl
m4_ifelse(mmux_libc_VALUEOF_$1,[[[MMUX_META_VALUE_UNDEFINED]]],m4_dnl
[[[/* #undef MMUX_HAVE_LIBC_$1 */]]],m4_dnl
[[[#define MMUX_HAVE_LIBC_$1	1
#define MMUX_LIBC_VALUEOF_$1	mmux_libc_VALUEOF_$1
#define MMUX_LIBC_$1	(mmux_libc_sysconf_parameter(mmux_libc_VALUEOF_$1))]]])]]])
m4_divert(0)m4_dnl
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_2_CHAR_TERM)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_2_C_BIND)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_2_C_DEV)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_2_C_VERSION)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_2_FORT_DEV)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_2_FORT_RUN)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_2_LOCALEDEF)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_2_PBS)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_2_PBS_ACCOUNTING)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_2_PBS_CHECKPOINT)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_2_PBS_LOCATE)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_2_PBS_MESSAGE)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_2_PBS_TRACK)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_2_SW_DEV)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_2_UPE)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_2_VERSION)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_ADVISORY_INFO)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_AIO_LISTIO_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_AIO_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_AIO_PRIO_DELTA_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_ARG_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_ASYNCHRONOUS_IO)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_ATEXIT_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_AVPHYS_PAGES)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_BARRIERS)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_BASE)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_BC_BASE_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_BC_DIM_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_BC_SCALE_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_BC_STRING_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_CHARCLASS_NAME_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_CHAR_BIT)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_CHAR_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_CHAR_MIN)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_CHILD_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_CLK_TCK)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_CLOCK_SELECTION)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_COLL_WEIGHTS_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_CPUTIME)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_C_LANG_SUPPORT)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_C_LANG_SUPPORT_R)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_DELAYTIMER_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_DEVICE_IO)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_DEVICE_SPECIFIC)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_DEVICE_SPECIFIC_R)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_EQUIV_CLASS_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_EXPR_NEST_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_FD_MGMT)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_FIFO)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_FILE_ATTRIBUTES)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_FILE_LOCKING)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_FILE_SYSTEM)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_FSYNC)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_GETGR_R_SIZE_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_GETPW_R_SIZE_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_HOST_NAME_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_INT_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_INT_MIN)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_IOV_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_IPV6)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_JOB_CONTROL)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_LEVEL1_DCACHE_ASSOC)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_LEVEL1_DCACHE_LINESIZE)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_LEVEL1_DCACHE_SIZE)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_LEVEL1_ICACHE_ASSOC)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_LEVEL1_ICACHE_LINESIZE)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_LEVEL1_ICACHE_SIZE)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_LEVEL2_CACHE_ASSOC)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_LEVEL2_CACHE_LINESIZE)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_LEVEL2_CACHE_SIZE)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_LEVEL3_CACHE_ASSOC)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_LEVEL3_CACHE_LINESIZE)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_LEVEL3_CACHE_SIZE)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_LEVEL4_CACHE_ASSOC)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_LEVEL4_CACHE_LINESIZE)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_LEVEL4_CACHE_SIZE)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_LINE_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_LOGIN_NAME_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_LONG_BIT)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_MAPPED_FILES)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_MB_LEN_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_MEMLOCK)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_MEMLOCK_RANGE)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_MEMORY_PROTECTION)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_MESSAGE_PASSING)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_MONOTONIC_CLOCK)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_MQ_OPEN_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_MQ_PRIO_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_MULTI_PROCESS)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_NETWORKING)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_NGROUPS_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_NL_ARGMAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_NL_LANGMAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_NL_MSGMAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_NL_NMAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_NL_SETMAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_NL_TEXTMAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_NPROCESSORS_CONF)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_NPROCESSORS_ONLN)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_NZERO)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_OPEN_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_PAGESIZE)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_PAGE_SIZE)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_PASS_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_PHYS_PAGES)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_PII)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_PII_INTERNET)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_PII_INTERNET_DGRAM)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_PII_INTERNET_STREAM)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_PII_OSI)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_PII_OSI_CLTS)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_PII_OSI_COTS)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_PII_OSI_M)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_PII_SOCKET)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_PII_XTI)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_PIPE)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_POLL)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_PRIORITIZED_IO)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_PRIORITY_SCHEDULING)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_RAW_SOCKETS)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_READER_WRITER_LOCKS)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_REALTIME_SIGNALS)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_REGEXP)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_REGEX_VERSION)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_RE_DUP_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_RTSIG_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_SAVED_IDS)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_SCHAR_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_SCHAR_MIN)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_SELECT)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_SEMAPHORES)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_SEM_NSEMS_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_SEM_VALUE_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_SHARED_MEMORY_OBJECTS)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_SHELL)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_SHRT_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_SHRT_MIN)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_SIGNALS)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_SIGQUEUE_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_SINGLE_PROCESS)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_SPAWN)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_SPIN_LOCKS)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_SPORADIC_SERVER)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_SSIZE_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_STREAMS)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_STREAM_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_SYMLOOP_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_SYNCHRONIZED_IO)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_SYSTEM_DATABASE)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_SYSTEM_DATABASE_R)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_THREADS)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_THREAD_ATTR_STACKADDR)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_THREAD_ATTR_STACKSIZE)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_THREAD_CPUTIME)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_THREAD_DESTRUCTOR_ITERATIONS)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_THREAD_KEYS_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_THREAD_PRIORITY_SCHEDULING)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_THREAD_PRIO_INHERIT)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_THREAD_PRIO_PROTECT)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_THREAD_PROCESS_SHARED)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_THREAD_SAFE_FUNCTIONS)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_THREAD_SPORADIC_SERVER)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_THREAD_STACK_MIN)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_THREAD_THREADS_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_TIMEOUTS)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_TIMERS)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_TIMER_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_TRACE)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_TRACE_EVENT_FILTER)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_TRACE_INHERIT)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_TRACE_LOG)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_TTY_NAME_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_TYPED_MEMORY_OBJECTS)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_TZNAME_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_T_IOV_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_UCHAR_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_UINT_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_UIO_MAXIOV)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_ULONG_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_USER_GROUPS)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_USER_GROUPS_R)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_USHRT_MAX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_V6_ILP32_OFF32)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_V6_ILP32_OFFBIG)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_V6_LP64_OFF64)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_V6_LPBIG_OFFBIG)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_VERSION)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_WORD_BIT)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_XBS5_ILP32_OFF32)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_XBS5_ILP32_OFFBIG)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_XBS5_LP64_OFF64)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_XBS5_LPBIG_OFFBIG)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_XOPEN_CRYPT)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_XOPEN_ENH_I18N)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_XOPEN_LEGACY)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_XOPEN_REALTIME)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_XOPEN_REALTIME_THREADS)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_XOPEN_SHM)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_XOPEN_UNIX)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_XOPEN_VERSION)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_XOPEN_XCU_VERSION)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_XOPEN_XPG2)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_XOPEN_XPG3)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_PARAMETER_CONSTANT(_SC_XOPEN_XPG4)

/* ------------------------------------------------------------------ */

m4_divert(-1)
m4_define([[[MMUX_LIBC_DEFINE_SYSTEM_STRING_CONFIGURATION_PARAMETER_CONSTANT]]],[[[m4_dnl
m4_ifelse(mmux_libc_VALUEOF_$1,[[[MMUX_META_VALUE_UNDEFINED]]],m4_dnl
[[[/* #undef MMUX_HAVE_LIBC_$1 */]]],m4_dnl
[[[#define MMUX_HAVE_LIBC_$1	1
#define MMUX_LIBC_VALUEOF_$1	mmux_libc_VALUEOF_$1
#define MMUX_LIBC_$1	(mmux_libc_sysconf_string_parameter(mmux_libc_VALUEOF_$1))]]])]]])
m4_divert(0)m4_dnl
MMUX_LIBC_DEFINE_SYSTEM_STRING_CONFIGURATION_PARAMETER_CONSTANT(_CS_LFS64_CFLAGS)
MMUX_LIBC_DEFINE_SYSTEM_STRING_CONFIGURATION_PARAMETER_CONSTANT(_CS_LFS64_LDFLAGS)
MMUX_LIBC_DEFINE_SYSTEM_STRING_CONFIGURATION_PARAMETER_CONSTANT(_CS_LFS64_LIBS)
MMUX_LIBC_DEFINE_SYSTEM_STRING_CONFIGURATION_PARAMETER_CONSTANT(_CS_LFS64_LINTFLAGS)
MMUX_LIBC_DEFINE_SYSTEM_STRING_CONFIGURATION_PARAMETER_CONSTANT(_CS_LFS_CFLAGS)
MMUX_LIBC_DEFINE_SYSTEM_STRING_CONFIGURATION_PARAMETER_CONSTANT(_CS_LFS_LDFLAGS)
MMUX_LIBC_DEFINE_SYSTEM_STRING_CONFIGURATION_PARAMETER_CONSTANT(_CS_LFS_LIBS)
MMUX_LIBC_DEFINE_SYSTEM_STRING_CONFIGURATION_PARAMETER_CONSTANT(_CS_LFS_LINTFLAGS)
MMUX_LIBC_DEFINE_SYSTEM_STRING_CONFIGURATION_PARAMETER_CONSTANT(_CS_PATH)

/* ------------------------------------------------------------------ */

m4_divert(-1)
m4_define([[[MMUX_LIBC_DEFINE_SYSTEM_PATHNAME_CONFIGURATION_PARAMETER_CONSTANT]]],[[[m4_dnl
m4_ifelse(mmux_libc_VALUEOF_$1,[[[MMUX_META_VALUE_UNDEFINED]]],m4_dnl
[[[/* #undef MMUX_HAVE_LIBC_$1 */]]],m4_dnl
[[[#define MMUX_HAVE_LIBC_$1	1
#define MMUX_LIBC_VALUEOF_$1	mmux_libc_VALUEOF_$1
#define MMUX_LIBC_$1	(mmux_libc_sysconf_pathname_parameter(mmux_libc_VALUEOF_$1))]]])]]])
m4_divert(0)m4_dnl
MMUX_LIBC_DEFINE_SYSTEM_PATHNAME_CONFIGURATION_PARAMETER_CONSTANT(_PC_ASYNC_IO)
MMUX_LIBC_DEFINE_SYSTEM_PATHNAME_CONFIGURATION_PARAMETER_CONSTANT(_PC_CHOWN_RESTRICTED)
MMUX_LIBC_DEFINE_SYSTEM_PATHNAME_CONFIGURATION_PARAMETER_CONSTANT(_PC_FILESIZEBITS)
MMUX_LIBC_DEFINE_SYSTEM_PATHNAME_CONFIGURATION_PARAMETER_CONSTANT(_PC_LINK_MAX)
MMUX_LIBC_DEFINE_SYSTEM_PATHNAME_CONFIGURATION_PARAMETER_CONSTANT(_PC_MAX_CANON)
MMUX_LIBC_DEFINE_SYSTEM_PATHNAME_CONFIGURATION_PARAMETER_CONSTANT(_PC_MAX_INPUT)
MMUX_LIBC_DEFINE_SYSTEM_PATHNAME_CONFIGURATION_PARAMETER_CONSTANT(_PC_NAME_MAX)
MMUX_LIBC_DEFINE_SYSTEM_PATHNAME_CONFIGURATION_PARAMETER_CONSTANT(_PC_NO_TRUNC)
MMUX_LIBC_DEFINE_SYSTEM_PATHNAME_CONFIGURATION_PARAMETER_CONSTANT(_PC_PATH_MAX)
MMUX_LIBC_DEFINE_SYSTEM_PATHNAME_CONFIGURATION_PARAMETER_CONSTANT(_PC_PIPE_BUF)
MMUX_LIBC_DEFINE_SYSTEM_PATHNAME_CONFIGURATION_PARAMETER_CONSTANT(_PC_PRIO_IO)
MMUX_LIBC_DEFINE_SYSTEM_PATHNAME_CONFIGURATION_PARAMETER_CONSTANT(_PC_REC_INCR_XFER_SIZE)
MMUX_LIBC_DEFINE_SYSTEM_PATHNAME_CONFIGURATION_PARAMETER_CONSTANT(_PC_REC_MAX_XFER_SIZE)
MMUX_LIBC_DEFINE_SYSTEM_PATHNAME_CONFIGURATION_PARAMETER_CONSTANT(_PC_REC_MIN_XFER_SIZE)
MMUX_LIBC_DEFINE_SYSTEM_PATHNAME_CONFIGURATION_PARAMETER_CONSTANT(_PC_REC_XFER_ALIGN)
MMUX_LIBC_DEFINE_SYSTEM_PATHNAME_CONFIGURATION_PARAMETER_CONSTANT(_PC_SYNC_IO)
MMUX_LIBC_DEFINE_SYSTEM_PATHNAME_CONFIGURATION_PARAMETER_CONSTANT(_PC_VDISABLE)

/* ------------------------------------------------------------------ */

m4_divert(-1)
m4_define([[[MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_LIMIT_RESOURCE_CONSTANT]]],[[[m4_dnl
m4_ifelse(mmux_libc_VALUEOF_$1,[[[MMUX_META_VALUE_UNDEFINED]]],m4_dnl
[[[/* #undef MMUX_HAVE_LIBC_$1 */]]],m4_dnl
[[[#define MMUX_HAVE_LIBC_$1	1
#define MMUX_LIBC_VALUEOF_$1	mmux_libc_VALUEOF_$1
#define MMUX_LIBC_$1	(mmux_libc_sysconf_resource_limit(mmux_libc_VALUEOF_$1))]]])]]])
m4_divert(0)m4_dnl
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_LIMIT_RESOURCE_CONSTANT(RLIMIT_AS)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_LIMIT_RESOURCE_CONSTANT(RLIMIT_CORE)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_LIMIT_RESOURCE_CONSTANT(RLIMIT_CPU)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_LIMIT_RESOURCE_CONSTANT(RLIMIT_DATA)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_LIMIT_RESOURCE_CONSTANT(RLIMIT_FSIZE)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_LIMIT_RESOURCE_CONSTANT(RLIMIT_LOCKS)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_LIMIT_RESOURCE_CONSTANT(RLIMIT_MEMLOCK)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_LIMIT_RESOURCE_CONSTANT(RLIMIT_MSGQUEUE)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_LIMIT_RESOURCE_CONSTANT(RLIMIT_NICE)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_LIMIT_RESOURCE_CONSTANT(RLIMIT_NOFILE)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_LIMIT_RESOURCE_CONSTANT(RLIMIT_NPROC)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_LIMIT_RESOURCE_CONSTANT(RLIMIT_RSS)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_LIMIT_RESOURCE_CONSTANT(RLIMIT_RTPRIO)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_LIMIT_RESOURCE_CONSTANT(RLIMIT_RTTIME)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_LIMIT_RESOURCE_CONSTANT(RLIMIT_SIGPENDING)
MMUX_LIBC_DEFINE_SYSTEM_CONFIGURATION_LIMIT_RESOURCE_CONSTANT(RLIMIT_STACK)

m4_ifelse(mmux_libc_VALUEOF_RLIM_INFINITY,[[[MMUX_META_VALUE_UNDEFINED]]],m4_dnl
[[[/* #undef MMUX_HAVE_LIBC_RLIM_INFINITY */]]],m4_dnl
[[[#define MMUX_HAVE_LIBC_RLIM_INFINITY	1
#define MMUX_LIBC_RLIM_INFINITY		(mmux_libc_rlim_literal(mmux_libc_VALUEOF_RLIM_INFINITY))
]]])


/** --------------------------------------------------------------------
 ** File lock type.
 ** ----------------------------------------------------------------- */

m4_divert(-1)
m4_define([[[MMUX_LIBC_DEFINE_FILE_LOCK_TYPE_CONSTANT]]],[[[m4_dnl
m4_ifelse(mmux_libc_VALUEOF_$1,[[[MMUX_META_VALUE_UNDEFINED]]],m4_dnl
[[[/* #undef MMUX_HAVE_LIBC_$1 */]]],m4_dnl
[[[#define MMUX_HAVE_LIBC_$1	1
#define MMUX_LIBC_VALUEOF_$1	mmux_libc_VALUEOF_$1
#define MMUX_LIBC_$1	(mmux_libc_file_lock_type(mmux_libc_VALUEOF_$1))]]])]]])
m4_divert(0)m4_dnl
MMUX_LIBC_DEFINE_FILE_LOCK_TYPE_CONSTANT(F_RDLCK)
MMUX_LIBC_DEFINE_FILE_LOCK_TYPE_CONSTANT(F_UNLCK)
MMUX_LIBC_DEFINE_FILE_LOCK_TYPE_CONSTANT(F_WRLCK)


/** --------------------------------------------------------------------
 ** Seek whence.
 ** ----------------------------------------------------------------- */

m4_divert(-1)
m4_define([[[MMUX_LIBC_DEFINE_SEEK_WHENCE_CONSTANT]]],[[[m4_dnl
m4_ifelse(mmux_libc_VALUEOF_$1,[[[MMUX_META_VALUE_UNDEFINED]]],m4_dnl
[[[/* #undef MMUX_HAVE_LIBC_$1 */]]],m4_dnl
[[[#define MMUX_HAVE_LIBC_$1	1
#define MMUX_LIBC_VALUEOF_$1	mmux_libc_VALUEOF_$1
#define MMUX_LIBC_$1	(mmux_libc_seek_whence(mmux_libc_VALUEOF_$1))]]])]]])
m4_divert(0)m4_dnl
MMUX_LIBC_DEFINE_SEEK_WHENCE_CONSTANT(SEEK_CUR)
MMUX_LIBC_DEFINE_SEEK_WHENCE_CONSTANT(SEEK_DATA)
MMUX_LIBC_DEFINE_SEEK_WHENCE_CONSTANT(SEEK_END)
MMUX_LIBC_DEFINE_SEEK_WHENCE_CONSTANT(SEEK_HOLE)
MMUX_LIBC_DEFINE_SEEK_WHENCE_CONSTANT(SEEK_SET)


/** --------------------------------------------------------------------
 ** Fcntl command.
 ** ----------------------------------------------------------------- */

m4_divert(-1)
m4_define([[[MMUX_LIBC_DEFINE_FCNTL_COMMAND_CONSTANT]]],[[[m4_dnl
m4_ifelse(mmux_libc_VALUEOF_$1,[[[MMUX_META_VALUE_UNDEFINED]]],m4_dnl
[[[/* #undef MMUX_HAVE_LIBC_$1 */]]],m4_dnl
[[[#define MMUX_HAVE_LIBC_$1	1
#define MMUX_LIBC_VALUEOF_$1	mmux_libc_VALUEOF_$1
#define MMUX_LIBC_$1	(mmux_libc_fcntl_command(mmux_libc_VALUEOF_$1))]]])]]])
m4_divert(0)m4_dnl
MMUX_LIBC_DEFINE_FCNTL_COMMAND_CONSTANT(F_DUPFD)
MMUX_LIBC_DEFINE_FCNTL_COMMAND_CONSTANT(F_GETFD)
MMUX_LIBC_DEFINE_FCNTL_COMMAND_CONSTANT(F_GETFL)
MMUX_LIBC_DEFINE_FCNTL_COMMAND_CONSTANT(F_GETLK)
MMUX_LIBC_DEFINE_FCNTL_COMMAND_CONSTANT(F_GETOWN)
MMUX_LIBC_DEFINE_FCNTL_COMMAND_CONSTANT(F_OFD_SETLK)
MMUX_LIBC_DEFINE_FCNTL_COMMAND_CONSTANT(F_OFD_SETLKW)
MMUX_LIBC_DEFINE_FCNTL_COMMAND_CONSTANT(F_OFD_GETLK)
MMUX_LIBC_DEFINE_FCNTL_COMMAND_CONSTANT(F_SETFD)
MMUX_LIBC_DEFINE_FCNTL_COMMAND_CONSTANT(F_SETFL)
MMUX_LIBC_DEFINE_FCNTL_COMMAND_CONSTANT(F_SETLK)
MMUX_LIBC_DEFINE_FCNTL_COMMAND_CONSTANT(F_SETLKW)
MMUX_LIBC_DEFINE_FCNTL_COMMAND_CONSTANT(F_SETOWN)


/** --------------------------------------------------------------------
 ** Ioctl command.
 ** ----------------------------------------------------------------- */

m4_divert(-1)
m4_define([[[MMUX_LIBC_DEFINE_IOCTL_COMMAND_CONSTANT]]],[[[m4_dnl
m4_ifelse(mmux_libc_VALUEOF_$1,[[[MMUX_META_VALUE_UNDEFINED]]],m4_dnl
[[[/* #undef MMUX_HAVE_LIBC_$1 */]]],m4_dnl
[[[#define MMUX_HAVE_LIBC_$1	1
#define MMUX_LIBC_VALUEOF_$1	mmux_libc_VALUEOF_$1
#define MMUX_LIBC_$1	(mmux_libc_ioctl_command(mmux_libc_VALUEOF_$1))]]])]]])
m4_divert(0)m4_dnl
MMUX_LIBC_DEFINE_IOCTL_COMMAND_CONSTANT(SIOCATMARK)


/** --------------------------------------------------------------------
 ** Interprocess signals.
 ** ----------------------------------------------------------------- */

#define MMUX_HAVE_LIBC_SIG_ZERO		1
#define MMUX_LIBC_VALUEOF_SIG_ZERO	0
#define MMUX_LIBC_SIG_ZERO		(mmux_libc_interprocess_signal(mmux_libc_VALUEOF_SIG_ZERO))

m4_divert(-1)
m4_define([[[MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT]]],[[[m4_dnl
m4_ifelse(mmux_libc_VALUEOF_$1,[[[MMUX_META_VALUE_UNDEFINED]]],m4_dnl
[[[/* #undef MMUX_HAVE_LIBC_$1 */]]],m4_dnl
[[[#define MMUX_HAVE_LIBC_$1	1
#define MMUX_LIBC_VALUEOF_$1	mmux_libc_VALUEOF_$1
#define MMUX_LIBC_$1	(mmux_libc_interprocess_signal(mmux_libc_VALUEOF_$1))]]])]]])
m4_divert(0)m4_dnl
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(NSIG)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(SIGFPE)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(SIGILL)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(SIGSEGV)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(SIGBUS)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(SIGABRT)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(SIGIOT)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(SIGTRAP)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(SIGEMT)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(SIGSYS)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(SIGTERM)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(SIGINT)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(SIGQUIT)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(SIGKILL)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(SIGHUP)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(SIGALRM)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(SIGVRALRM)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(SIGPROF)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(SIGIO)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(SIGURG)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(SIGPOLL)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(SIGCHLD)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(SIGCLD)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(SIGCONT)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(SIGSTOP)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(SIGTSTP)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(SIGTTIN)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(SIGTTOU)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(SIGPIPE)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(SIGLOST)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(SIGXCPU)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(SIGXSFZ)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(SIGUSR1)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(SIGUSR2)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(SIGWINCH)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_CONSTANT(SIGINFO)

m4_divert(-1)
m4_define([[[MMUX_LIBC_DEFINE_SIGACTION_FLAG_CONSTANT]]],[[[m4_dnl
m4_ifelse(mmux_libc_VALUEOF_$1,[[[MMUX_META_VALUE_UNDEFINED]]],m4_dnl
[[[/* #undef MMUX_HAVE_LIBC_$1 */]]],m4_dnl
[[[#define MMUX_HAVE_LIBC_$1	1
#define MMUX_LIBC_$1		mmux_libc_VALUEOF_$1]]])]]])
m4_divert(0)m4_dnl
MMUX_LIBC_DEFINE_SIGACTION_FLAG_CONSTANT(SA_NOCLDSTOP)
MMUX_LIBC_DEFINE_SIGACTION_FLAG_CONSTANT(SA_NOCLDWAIT)
MMUX_LIBC_DEFINE_SIGACTION_FLAG_CONSTANT(SA_NODEFER)
MMUX_LIBC_DEFINE_SIGACTION_FLAG_CONSTANT(SA_ONSTACK)
MMUX_LIBC_DEFINE_SIGACTION_FLAG_CONSTANT(SA_RESETHAND)
MMUX_LIBC_DEFINE_SIGACTION_FLAG_CONSTANT(SA_RESTART)
MMUX_LIBC_DEFINE_SIGACTION_FLAG_CONSTANT(SA_RESTORER)
MMUX_LIBC_DEFINE_SIGACTION_FLAG_CONSTANT(SA_SIGINFO)
MMUX_LIBC_DEFINE_SIGACTION_FLAG_CONSTANT(SA_UNSUPPORTED)
MMUX_LIBC_DEFINE_SIGACTION_FLAG_CONSTANT(SA_EXPOSE_TAGBITS)

/* ------------------------------------------------------------------ */

m4_divert(-1)
m4_define([[[MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT]]],[[[m4_dnl
m4_ifelse(mmux_libc_VALUEOF_$1,[[[MMUX_META_VALUE_UNDEFINED]]],m4_dnl
[[[/* #undef MMUX_HAVE_LIBC_$1 */]]],m4_dnl
[[[#define MMUX_HAVE_LIBC_$1	1
#define MMUX_LIBC_VALUEOF_$1	mmux_libc_VALUEOF_$1
#define MMUX_LIBC_$1	(mmux_libc_si_code(mmux_libc_VALUEOF_$1))]]])]]])
m4_divert(0)m4_dnl

MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(SI_USER)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(SI_KERNEL)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(SI_QUEUE)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(SI_TIMER)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(SI_MESGQ)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(SI_ASYNCIO)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(SI_SIGIO)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(SI_TKILL)

MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(ILL_ILLOPC)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(ILL_ILLOPN)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(ILL_ILLADR)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(ILL_ILLTRP)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(ILL_PRVOPC)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(ILL_PRVREG)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(ILL_COPROC)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(ILL_BADSTK)

MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(FPE_INTDIV)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(FPE_INTOVF)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(FPE_FLTDIV)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(FPE_FLTOVF)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(FPE_FLTUND)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(FPE_FLTRES)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(FPE_FLTINV)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(FPE_FLTSUB)

MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(SEGV_MAPERR)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(SEGV_ACCERR)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(SEGV_BNDERR)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(SEGV_PKUERR)

MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(BUS_ADRALN)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(BUS_ADRERR)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(BUS_OBJERR)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(BUS_MCEERR_AR)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(BUS_MCEERR_AO)

MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(TRAP_BRKPT)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(TRAP_TRACE)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(TRAP_BRANCH)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(TRAP_HWBKPT)

MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(CLD_EXITED)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(CLD_KILLED)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(CLD_DUMPED)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(CLD_TRAPPED)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(CLD_STOPPED)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(CLD_CONTINUED)

MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(POLL_IN)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(POLL_OUT)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(POLL_MSG)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(POLL_ERR)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(POLL_PRI)
MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(POLL_HUP)

MMUX_LIBC_DEFINE_INTERPROCESS_SIGNAL_SI_CODE_CONSTANT(SYS_SECCOMP)


/** --------------------------------------------------------------------
 ** Enumerations.
 ** ----------------------------------------------------------------- */

m4_divert(-1)

m4_define([[[MMUX_LIBC_DEFINE_ENUM_CONSTANT]]],[[[m4_ifelse(mmux_libc_VALUEOF_$1,[[[MMUX_META_VALUE_UNDEFINED]]],m4_dnl
[[[/* #undef MMUX_HAVE_LIBC_$1 */]]],m4_dnl
[[[#define MMUX_HAVE_LIBC_$1	1
  MMUX_LIBC_$1 = mmux_libc_VALUEOF_$1,]]])]]])

m4_define([[[MMUX_LIBC_DEFINE_ULONG_CPP_CONSTANT]]],[[[m4_ifelse(mmux_libc_VALUEOF_$1,[[[MMUX_META_VALUE_UNDEFINED]]],m4_dnl
[[[/* #undef MMUX_HAVE_LIBC_$1 */]]],m4_dnl
[[[#define MMUX_HAVE_LIBC_$1	1
#define MMUX_LIBC_$1		mmux_libc_VALUEOF_$1[[[]]]UL]]])]]])
m4_divert(0)m4_dnl

/* ------------------------------------------------------------------ */

typedef enum mmux_libc_constant_t {
MMUX_LIBC_DEFINE_ENUM_CONSTANT(AT_EACCESS)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(AT_EMPTY_PATH)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(AT_NOAUTOMOUNT)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(AT_REMOVEDIR)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(AT_SYMLINK_FOLLOW)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(AT_SYMLINK_NOFOLLOW)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(AT_FDCWD)

MMUX_LIBC_DEFINE_ENUM_CONSTANT(EOF)

MMUX_LIBC_DEFINE_ENUM_CONSTANT(FD_CLOEXEC)

MMUX_LIBC_DEFINE_ENUM_CONSTANT(MAXSYMLINKS)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(O_ACCMODE)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(O_APPEND)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(O_ASYNC)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(O_CLOEXEC)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(O_CREAT)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(O_DIRECTORY)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(O_DIRECT)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(O_DSYNC)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(O_EXCL)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(O_EXEC)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(O_EXLOCK)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(O_FSYNC)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(O_IGNORE_CTTY)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(O_LARGEFILE)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(O_NDELAY)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(O_NOATIME)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(O_NOCTTY)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(O_NOFOLLOW)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(O_NOLINK)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(O_NONBLOCK)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(O_NOTRANS)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(O_PATH)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(O_RDONLY)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(O_RDWR)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(O_READ)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(O_SHLOCK)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(O_SYNC)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(O_TMPFILE)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(O_TRUNC)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(O_WRITE)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(O_WRONLY)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(RENAME_EXCHANGE)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(RENAME_NOREPLACE)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(RENAME_WITHEOUT)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(RESOLVE_BENEATH)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(RESOLVE_IN_ROOT)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(RESOLVE_NO_MAGICLINKS)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(RESOLVE_NO_SYMLINKS)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(RESOLVE_NO_XDEV)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(RESOLVE_CACHED)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(S_IRGRP)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(S_IROTH)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(S_IRUSR)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(S_IRWXG)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(S_IRWXO)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(S_IRWXU)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(S_ISGID)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(S_ISUID)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(S_ISVTX)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(S_IWGRP)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(S_IWOTH)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(S_IWUSR)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(S_IXGRP)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(S_IXOTH)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(S_IXUSR)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(F_OK)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(R_OK)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(W_OK)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(X_OK)

MMUX_LIBC_DEFINE_ENUM_CONSTANT(MFD_CLOEXEC)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(MFD_ALLOW_SEALING)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(MFD_HUGETLB)

MMUX_LIBC_DEFINE_ENUM_CONSTANT(RWF_APPEND)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(RWF_DSYNC)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(RWF_HIPRI)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(RWF_NOWAIT)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(RWF_SYNC)

MMUX_LIBC_DEFINE_ENUM_CONSTANT(IFNAMSIZ)
#define MMUX_HAVE_LIBC_MSG_ZERO		1
  MMUX_LIBC_MSG_ZERO = 0,
MMUX_LIBC_DEFINE_ENUM_CONSTANT(MSG_CONFIRM)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(MSG_DONTROUTE)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(MSG_DONTWAIT)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(MSG_EOR)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(MSG_MORE)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(MSG_NOSIGNAL)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(MSG_OOB)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(MSG_PEEK)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(SOL_SOCKET)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(SO_BROADCAST)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(SO_DEBUG)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(SO_DONTROUTE)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(SO_ERROR)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(SO_KEEPALIVE)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(SO_LINGER)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(SO_OOBINLINE)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(SO_RCVBUF)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(SO_REUSEADDR)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(SO_SNDBUF)
#define MMUX_HAVE_LIBC_SO_STYLE		MMUX_HAVE_LIBC_SO_TYPE
#define MMUX_LIBC_SO_STYLE		MMUX_LIBC_SO_TYPE
MMUX_LIBC_DEFINE_ENUM_CONSTANT(SO_TYPE)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(AI_ADDRCONFIG)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(AI_ALL)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(AI_CANONIDN)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(AI_CANONNAME)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(AI_IDN)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(AI_NUMERICSERV)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(AI_PASSIVE)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(AI_V4MAPPED)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(NI_DGRAM)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(NI_IDN)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(NI_NAMEREQD)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(NI_NOFQDN)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(NI_NUMERICHOST)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(NI_NUMERICSERV)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(IPPORT_BIFFUDP)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(IPPORT_CMDSERVER)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(IPPORT_DAYTIME)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(IPPORT_DISCARD)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(IPPORT_ECHO)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(IPPORT_EFSSERVER)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(IPPORT_EXECSERVER)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(IPPORT_FINGER)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(IPPORT_FTP)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(IPPORT_LOGINSERVER)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(IPPORT_MTP)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(IPPORT_NAMESERVER)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(IPPORT_NETSTAT)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(IPPORT_RESERVED)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(IPPORT_RJE)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(IPPORT_ROUTESERVER)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(IPPORT_SMTP)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(IPPORT_SUPDUP)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(IPPORT_SYSTAT)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(IPPORT_TELNET)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(IPPORT_TFTP)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(IPPORT_TIMESERVER)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(IPPORT_TTYLINK)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(IPPORT_USERRESERVED)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(IPPORT_WHOIS)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(IPPORT_WHOSERVER)

MMUX_LIBC_DEFINE_ENUM_CONSTANT(P_ALL)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(P_PID)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(P_PIDFD)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(P_PGID)

MMUX_LIBC_DEFINE_ENUM_CONSTANT(WEXITED)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(WNOWAIT)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(WSTOPPED)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(WNOHANG)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(WCONTINUED)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(WUNTRACED)

MMUX_LIBC_DEFINE_ENUM_CONSTANT(CLOCKS_PER_SEC)

MMUX_LIBC_DEFINE_ENUM_CONSTANT(SFD_NONBLOCK)
MMUX_LIBC_DEFINE_ENUM_CONSTANT(SFD_CLOEXEC)

} mmux_libc_constant_t;


/** --------------------------------------------------------------------
 ** Done.
 ** ----------------------------------------------------------------- */

#ifdef __cplusplus
} // extern "C"
#endif

#endif /* MMUX_CC_LIBC_CONSTANTS_H */

/* end of file */
